spring:
  application:
    name: 'ac-control'
application:
  mqtt:
    url: ${mqtt.url}
    subClientId: mySubClientId
    pubClientId: myPubClientId
  device:
    id:  ${device.id}
    name:  ${device.name}
  discovery-topic: 'homeassistant/climate/${application.device.id}/climate/config'
  ir-remote-control:
    output-topic: ${output.topic}
    commands:
      power:
        input-topic: 'climate/${application.device.name}/${application.device.id}/power'
        vendors:
          Midea:
            ON: 'Cc8RzxEZAlQGGQJAAUAHQAPAAeATC8AbQAdAA0ABQAfgCwNAAUAX4A8B4AMbQAvAA+ADAeATEwHPEUABARkCQCNAAUAHQAPAAeATC8AbQAdAA0ABQAfgCwNAAUAX4A8B4AMbQAvAA+ADAeAQEwIGGQI='
            OFF: 'CdsR2xETAmEGEwJAAUAHQAPAAeATC8Ab4AMHQAvAA0ABwAtAB+AHAeADE0ALwAPgFwHAJ+ADBwHbEUABARMCQBNAAUAHQAPAAeAHCwJVAhNgAUAXQANAAeADB0ALwANAAcALQAfgBwHgAxNAC8ADwAHAa+AHAcAnC2EGEwJhBhMCYQYTAg=='
      mode:
        input-topic: 'climate/${application.device.name}/${application.device.id}/mode/set'
        vendors:
          Midea:
            heat: 'C9IR0hFEAisGAwIDAkAHgANAC0ADQA9ABwADIAHgBwvAD0AHQAMDAwJEAkAH4AkDAwMCAwKAFwADYAFAB+AFAwErBoADgBcBAwKADwMDAgMCwBOABwErBoAD4AUPAwMC0hFAAQlEAisGRAIDAkQCQAdAAwADYAEJRAIrBgMCAwJEAkAD4AcLBysGRAIDAkQCQAdAA+ADC0AP4AMDwBtAB4ADQAHACwFEAsArQAtAAwIrBgNgAwQDAkQCA2ABQAcBRAKAFwJEAgNgAQlEAisGRAIrBkQC'
            cool: 'DcQRxBFDAjMGQwIEAkMCQAdAA0ALQAPgEwsFMwYEAgQCQAeAA4ALBAQCMwZD4AgDAAQgAUAXAQQC4AcDQAEBQwJAG0ADQAuAA0ABwAvgAQcCMwYEIAPgAwdACwNDAsQRQAEBQwJACwMEAkMCQAdAA0ALAAQgAeAJC0ABAUMCQBdAA+ANCwEEAuAFA0AnBwQCMwYEAgQCQAvAA0ABgAsBMwaAAwAEYAFAB8ADQAHgAQuAJ+AGBwIGBAI='
            dry: 'CdcR1xEbAk0GGwJAAUAHQAPAAeATC8AbwAfAAUAP4BMD4AsBwC/gAwFAE+AHAUATwANAAcALAdcRQAEBGwJAD0ABQAdAA8AB4BMLwBvAB8ABQA/gEwPgCwHAL+ADAUAT4AcBQBPAAwsbAhsCTQYbAk0GGwI='
            fan_only: 'CckRyREgAjkGIAJAAUAHQAMEIAJWAiAgAeAJC4ABQBdAA0ABQAdAA0ABQAfgCwNAAQE5BoBT4AsBATkG4AEDwAFAE+ALAUAXQAMDIAJWAkAHBTkGVgLJEUABQAsBIAJAAUAHBDkGVgIgoAEDOQYgAsAB4AcLwA9AB0ADQAFAB+ALA0ABQBfgDwFAG8ADASACgH9AD+ALAUAXQAMLIAIgAjkGIAI5BiAC'
            auto: 'CdUR1REdAj0GHQJAAUAHBD0GUQIdoAHgEQtAGwEdAkABAT0GwC+ABwE9BuAHAwBRoBOAB+AJAYAXQB8AHaABAz0GHQLgCwFAF0ADQAFAB8ADAdURQAEDHQI9BoBDAT0GgAPAAUAPwAHgBwvAD8AHwAFAD+ATA0ABgG3gAQHAL8ABQA/gCwFAF0ADQAELPQYdAj0GHQI9Bh0C'
            'off': 'CdsR2xETAmEGEwJAAUAHQAPAAeATC8Ab4AMHQAvAA0ABwAtAB+AHAeADE0ALwAPgFwHAJ+ADBwHbEUABARMCQBNAAUAHQAPAAeAHCwJVAhNgAUAXQANAAeADB0ALwANAAcALQAfgBwHgAxNAC8ADwAHAa+AHAcAnC2EGEwJhBhMCYQYTAg=='
      temperature:
        input-topic: 'climate/${application.device.name}/${application.device.id}/temperature/set'
        vendors:
          Midea:
            20: 'ETMRMxEuAm4G9wEuAvcBbgYuAkADQAED9wEuAsALQAFAC0ATQAFACwFuBoANQAcFbgYuAi4CQAdAAwMuAm4GwAeACwcuAvcBbgb3AUAH4AEDQAFAD0ABQAcB9wGAIwEuAkAHQAMHLgL3AfcBLgJAC0ADAy4C9wGAB0ABgAtADwdvFDMRMxH3AUAL4AMXQAtAA8AX4AsLwBtAB0ADwCNAC+AHA8AbQAfgEQMBLgJANwMuAvcBQAdAA0ALQANAC0ADgAtABQ33AS4C9wFuBvcBbgb3AQ=='
            21: 'Cd8R3xETAmQGEwJAAUAHQAPAAeATC8AbQAdAA0ABQAfgCwNAAUAX4BMBQB9AA0ABQAdAA8AB4BMLQBsB3xFAAQETAkALQAFAB0ADwAHgEwvAG0AHQANAAUAH4AsDQAFAF+ALAQJVAhNgAUAfQANAAUAHQAPgARsBkQHgAQsBEwLAAQdkBhMCZAYTAg=='
            22: 'CdQR1BETAmQGEwJAAUAHQAPAAeATC8AbQAdAA0ABQAfgCwNAAUAX4BMBQB/gBwPAAUAX4AsBQBdAAwHUEUABARMCQAtAAUAHQAPAAeATC8AbQAdAA0ABQAfgCwNAAUAXwAECVgIT4AgBQB/gBwPAAUAX4AsBB2QGEwJkBhMC'
            23: 'CScRJxEVAl8GFQJAAUAHQAPAAeATC8AbQAdAA0ABQAfgCwNAAUAX4BMBwB9AB8ADwAFAD0ABwAfAAUAPQAMHahQnEScRFQJAC0ABQAdAA8AB4BMLwBtAB0ADQAFAB+ALA0ABQBcCVAIV4AQB4AMPQB9AAUAHwAPAAUAPQAHAB8ABB18GFQJfBhUC'
            24: 'CS8RLxESAmMGEgJAAUAHQAPAAeATC8AbQAdAA0ABQAfgCwNAAUAX4BMB4AMfQAtAA8ABwAtAB0ADQAEDVgISAkALQAMHjxQvES8REgJAC0ABQAdAA8AB4BMLwBtAB0ADQAFAB+ALA0ABQBdAAUB/4AMBwA/AH0ABQAtAA8ABwAtAB0ADwAEHYwYSAmMGEgI='
            25: 'DcMRwxE9AjIGPQL4AT0CQAdAA0ALQAPgEwvAG0AHQAPAL0AL4AcDwBtAB+ALA8AvwBvgBw/gBRcD+AH4AYATATIGgAMBwxFAAQE9AkAPQBtAB0ADQAtAA+ATC8AbQAdAAwU9AvgBMgbAAwE9AuADAwP4AT0CQA9AB+ALA0AbQAMHPQL4AfgBPQJAC0ADQAvgAwMJMgb4ATIGPQL4AYADBzIGPQIyBj0C'
            26: 'CckRyREXAloGFwJAAUAHQAPAAeATC8AbQAdAA0ABQAfgCwNAAUAX4A8BQBtAA0ABQAfAA+AHAUAX4AMBQA9AAwHJEUABARcCQAtAAUAHQAPAAeATC8AbQAdAA0ABQAfgCwNAAUAX4A8BQBtAA0ABQAfAA+AHAUAX4AMBB1oGFwJaBhcC'
            27: 'CR4RHhEHAmcGBwJAAUAHQANAAQNEAgcCwAtAAUALQBNAAUALQANAAUAHQANAG0AH4AsDQAFAF8ABQCvgAwHAG0AXQAvAA0APQANAAcATQAFAE0ADwBMHlRQeER4RBwJAD0ABQAdAA0AjQANAC0ABwAtAB0ADQBdAA+APC0Ab4AMDwCdAAUALwANAAUALQCtAB0ADQAvAA0APQANAAeADE8ABB2cGBwJnBgcC'
            28: 'DcQRxBFBAiwGQQL6AUECQAdAA0ALQAPgDQsB+gFAF0ADA/oBQQJAB0AD4AMLQA/gAwPAG0AH4AsDQCvgAxdAD0AD4AsT4AMXQAtAAwHEEUABAUECQAtAMwksBvoBLAZBAvoBgAPgCQtAAUAXCfoBLAZBAvoBQQJAB0AD4AMLQA/gAwPAG0AH4AsDQCsB+gFAAUAHC0ECLAb6ASwGQQL6AUABQAcHQQIsBvoBLAZABwNBAvoBgAMHLAZBAiwGQQI='
            29: 'DcoRyhFJAkIGCAJJAggCQAdAA0ALQAFAC8AB4AcLQA9AJ0AHQANAAUAH4AsDwCdAB4ABwAlABwFJAkAzAQgCwAcBCAJAD0ADAwgCSQLAA4APAQgCgAcCSQIIIAECQgZJYAMByhFAAQdJAkIGCAIIAkAHgANAC0ADQA9ABwAIIAHgAQsBSQJAC0AD4A8LQBvgAwOAJwAIYAcBCAJAA8ABgAvAG+ADBwRCBkkCCOAAAQdJAkIGCAIIAsAHQAEJSQJCBggCQgZJAg=='
            30: 'DdIR0hE+AkIG+QE+AvkBQAdAA0ALQAPACwP5AT4C4AELAfkBQAtAAwM+AvkBQAdAAwM+Aj4CQAfgCwMDPgL5AUAXQAcDPgI+AoAFQAGACYAbAT4CQAfgAwML+QE+Aj4C+QH5AT4CQBcJPgL5AfkBPgI+AkAFC/kBQgY+AkIG+QHSEUABQAsFPgL5AT4CQAcHQgb5AfkBPgJAAwNCBj4CQAdAA+AHC8APQAdAA8AjQAvgBwPAG0AH4AsDQC9AF0AH4AMDQBPAA0AXwAtABws+AvkBQgY+AkIGPgI='
      fan:
        input-topic: 'climate/${application.device.name}/${application.device.id}/fan/set'
        vendors:
          Midea:
            low: 'CSgRKBEOAmgGDgJAAUAHQAPAAeATC8AbQAdAA8ABQAvgBwNAAcAT4AsBQBsCVQIOYAFAC8ADwBNAAeATEweCFCgRKBEOAkAjQAFAB0ADQAFAQ+ALC0ABQBdAA0ABQAdAA0AvQAFAC+AHA0AbwBPgCwFAG8ABQAvAA8AB4A8/B2gGDgJoBg4C'
            medium: 'CdUR1RESAmMGEgJAAUAHQAPAAeATC8Ab4AsHQBPgBwNAAUAT4AsB4AMXQAvAA+ADAeATEwHVEUABARICQCNAAUAHQAPAAeATC8Ab4AsHQBPgBwMDVQISAkATQAFAC8ABQAvAF0ABQAvAA+ADAeADE0AzCxICEgJjBhICYwYSAg=='
            high: 'CdQR1BEdAkcGHQJAAUAHQAPAAeATC8AbgAcCWQIdIAFAC+ATA+APAUAzwAFAC8AD4AMB4BMTAdQRQAEBHQJAI0ABQAdAA8AB4BMLwBvAB0ABQAvgEwPgDwFAM8ABQAvAA+ADAeAQEwIGHQI='
            auto: 'DcQRxBFEAi4G/wFEAv8BQAdAAwH/AUANAUQC4AELB/8BLgZEAv8BgANAC0ADQA9AB0AD4AMLQA/gAwPAG0AHAf8BQAFAB+ABA0ArwA9AC8ADwBNAB+ANEwf/AS4GRALEEUABAUQCQAsN/wFEAi4G/wEuBkQC/wFAAwH/AeABCwFEAuAHC8APQAdAA8AjQAvgBwPAG0AH4AEDQAGADwcuBv8B/wFEAkADQAsBLgZABwNEAv8BwAMB/wFAD0ADAf8BwAMJ/wEuBkQCLgb/AQ=='


