services:
  ac-control:
    image: tabakov/ac-control:latest
    environment:
      - MQTT_URL=tcp://192.168.100.115:1883
      - DEVICE_ID=0xa5c13813743bd4a2
      - DEVICE_NAME=Medea
    restart: unless-stopped